const items = [
  {
    id: 1,
    title: 'ReactJs Developer',
    category: 'Web Development',
    price: 12999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363568/course/react_rzjtau.png',
    desc: `As a React developer, you work in a comprehensive JavaScript library known as React. Your responsibilities are to design, develop, and implement this front-end technology for businesses.`,
  },
  {
    id: 2,
    title: 'Back End Developer',
    category: 'Web Development',
    price: 15999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363568/course/bed_gvfqdm.png',
    desc: `A back-end developer builds and maintains the technology that powers those components which, together, enable the user-facing side of the website to even exist in the first place. `,
  },
  {
    id: 3,
    title: 'MERN Stack Developer',
    category: 'Web Development',
    price: 26999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363568/course/mern_qkqkco.png',
    desc: `MERN is the acronym for MongoDB, Express JS, React JS and Node JS. The MERN stack is a combination of the above technologies, all based on JavaScript, used to build advanced web applications.`,
  },
  {
    id: 4,
    title: 'Data Analyst',
    category: 'Analytics',
    price: 7999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363567/course/da_eftrbr.png',
    desc: `A data analyst gathers, cleans, and studies data sets to help solve problems. ... A data analyst collects, cleans, and interprets data sets in order to answer a question or solve a problem.`,
  },
  {
    id: 5,
    title: 'Machine Learning',
    category: 'Analytics',
    price: 16999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363567/course/ml_xtp5uq.png',
    desc: `A machine learning engineer (ML engineer) is a person in IT who focuses on researching, building and designing self-running artificial intelligence (AI) systems to automate predictive models. `,
  },
  {
    id: 6,
    title: 'Data Scientist',
    category: 'Analytics',
    price: 24999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363567/course/ds_znf8o9.png',
    desc: `Data scientists are big data wranglers, gathering and analyzing large sets of structured and unstructured data. They analyze, process, and model data then interpret the results to create actionable plans for companies and other organizations.`,
  },
  {
    id: 7,
    title: 'DS & Algorithms',
    category: 'Programming',
    price: 17999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363567/course/dsa_vvyggf.png',
    desc: `A data structure is a named location that can be used to store and organize data. And, an algorithm is a collection of steps to solve a particular problem. Learning data structures and algorithms allow us to write efficient and optimized computer programs.`,
  },
  {
    id: 8,
    title: 'System Design',
    category: 'Programming',
    price: 15999,
    img: 'https://res.cloudinary.com/vijayawada/image/upload/v1626363567/course/sd_maf7mu.png',
    desc: `Systems design is the process of defining the architecture, product design, modules, interfaces, and data for a system to satisfy specified requirements. Systems design could be seen as the application of systems theory to product development.`,
  },
];

export default items;